### ISSUE TITLE
Use rollup

### ISSUE THREAD

**Issue by paulmillr** [lrvick/nodesb#1]
Hi @lrvick 

Just wanted to mention that there's a tool called Rollup (https://rollupjs.org/) which allows to create single JS files from tons of npm (etc) dependencies.

It's very useful and configurable. You can compile separate files from a node/browser, and you can compile code that works in both cases — even though browsers don't support common.js modules from node

**Comment by lrvick** [comment]
That might be an interesting step to do before the compilation for a smaller bundle. Will take a look!
